#开发环境配置

server:
  # 服务端口
  port: 5000


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: "root"
    password: "19930123"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easy_jmeter?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF8&allowPublicKeyRetrieval=true
  data:
    mongodb:
      database: easyJmeter
      host: 127.0.0.1
      port: 27017
      username: admin
      password: Admin@123456
      authentication-database: admin
  influx:
    url: http://localhost:8086
    user: admin
    password: Admin@123456
    token: 78cI854nWvFxIyn2crSaZo0kow3R--4eMW-nYvTC7wNeiq-NrFBdq4WvjBwcNCiN1X__37bnOhEdwRvPfKGhMw==
    database: mybucket

# 开启权限拦截
auth:
  enabled: true

# 开启登录要求验证码
login-captcha:
  enabled: false
  secret: "m49CPM5ak@MDXTzbbT_ZEyMM3KBsBn!h"

# 开启http请求日志记录
request-log:
  enabled: true


logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    com.zhao.easyJmeter.mapper: debug
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

minio:
  endpoint: http://localhost:9000
  bucketName: easy-jmeter
  accessKey: admin
  secretKey: Admin@123456

swagger:
  enable: true

socket:
  server:
    host: 0.0.0.0
    port: 9002
    enable: true
  client:
    serverUrl: http://127.0.0.1:9002
    enable: false

cron:
  heartBeat: "0 0/1 * * * ?"
  deleteTaskRecordStorage: "0 0 1 ? * MON"
  recordStatistics: "0 0/30 * * * ? "
  jmeterLogClear: "0 0 2 ? * *"